services:
  build_azure_updates_feed:
    container_name: "build_azure_updates_feed"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229 # for node debug
    command: ["npm", "run", "dev"]
